title: Zhihan Guo
logo: /assets/img/zhihan.jpg
description: PhD student at the Department of Computer Science and Engineering, the Chinese University of Hong Kong.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
